default: &default
  adapter: <%= ENV['DB_ADAPTER'] %>
  encoding: unicode
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV.fetch('DB_HOST') { 'localhost' } %>
  port: <%= ENV['DB_PORT'] %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: my_api_development

test:
  <<: *default
  database: my_api_test

production:
  encoding: unicode
  adapter: <%= Rails.application.credentials.database.adapter %>
  database: <%= Rails.application.credentials.database.name %>
  username: <%= Rails.application.credentials.database.user %>
  password: <%= Rails.application.credentials.database.password %>
  host: <%= Rails.application.credentials.database.host || 'localhost' %>
  port: <%= Rails.application.credentials.database.port %>
