default: &default
  adapter: <%= Rails.application.credentials.database.adapter %>
  encoding: <%= Rails.application.credentials.database.encoding %>
  database: <%= "my_api_#{ENV['RAILS_ENV']}" %>
  username: <%= Rails.application.credentials.database.user %>
  password: <%= Rails.application.credentials.database.password %>
  host: <%= Rails.application.credentials.database.host || 'localhost' %>
  port: <%= Rails.application.credentials.database.port %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default

test:
  <<: *default

production:
  database: <%= Rails.application.credentials.database.name %>
  <<: *default
